[platformio]
default_envs = esp32-s3-dev

[env:esp32-s3-dev]
platform = espressif32@7.0.1
board = freenove_esp32_s3_wroom
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.psram = enable
board_build.psram_mode = opi
board_build.psram_size = 8MB
board_build.psram_type = opi_psram_8mb
board_arduino.psram_enable = true
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time

lib_deps =
    fastled/FastLED @ ^3.9.12
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.3

build_flags =
    -DBOARD_HAS_PSRAM
    -DCONFIG_SPIRAM_SUPPORT
    -DCONFIG_SPIRAM_MODE_OCT=1
    -DCONFIG_SPIRAM_TYPE_ESPPSRAM64=1
    -DCONFIG_SPIRAM_SIZE=8
    -DESP32S3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1